# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 12:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('receiver_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6536\u8d27\u4eba\u59d3\u540d')),
                ('telephone_number', models.CharField(max_length=11, null=True, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u57ce\u5e02')),
                ('address', models.CharField(blank=True, max_length=70, null=True, verbose_name='\u8be6\u7ec6\u5730\u5740')),
                ('gender', models.CharField(choices=[('0', '\u5973'), ('1', '\u7537')], default='0', max_length=3, verbose_name='\u6027\u522b')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65e5\u671f')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='\u9a8c\u8bc1\u7801')),
                ('email', models.EmailField(max_length=30, verbose_name='\u90ae\u7bb1')),
                ('send_type', models.CharField(choices=[('0', '\u6ce8\u518c'), ('1', '\u627e\u56de\u5bc6\u7801')], max_length=5, verbose_name='\u64cd\u4f5c\u7c7b\u578b')),
                ('send_date', models.DateTimeField(auto_now=True, verbose_name='\u53d1\u9001\u7684\u65f6\u95f4')),
            ],
            options={
                'ordering': ('send_date',),
                'verbose_name': '\u90ae\u7bb1\u9a8c\u8bc1',
                'verbose_name_plural': '\u90ae\u7bb1\u9a8c\u8bc1',
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='\u6536\u8d27\u4eba\u540d\u5b57')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u57ce\u5e02')),
                ('address', models.CharField(max_length=70, null=True, verbose_name='\u8be6\u7ec6\u5730\u5740')),
                ('telephone', models.CharField(max_length=11, null=True, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u6237\u62e5\u6709\u7740')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': '\u6536\u8d27\u4eba',
                'verbose_name_plural': '\u6536\u8d27\u4eba',
            },
        ),
    ]
