# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receiver_id',
            field=models.IntegerField(default=0, verbose_name='\u9ed8\u8ba4\u7684\u6536\u8d27\u4ebaID'),
        ),
    ]
