# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='\u5546\u54c1\u70b9\u51fb\u91cf'),
        ),
    ]
